site_name: Gaia Cycle Documentation

theme:
 name: material
 language: en
 palette:
  # Palette toggle for light mode
  - scheme: default
    toggle:
     icon: material/weather-night
     name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
     icon: material/weather-sunny
     name: Switch to light mode
 font:
  text: Roboto
  code: Roboto Mono
 features:
  - navigation.tabs
  - navigation.expand
  - content.code.copy
  - content.code.annotate
  - navigation.sections
  - navigation.indexes
  - navigation.path
  - navigation.top
  - navigation.instant
extra:
 generator: false
 navigation:
  previous: true
  next: true
 social:
  - icon: fontawesome/brands/github
    link: https://github.com/MarieBelle88/GaiasCycle
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/bbaheer/
copyright: Copyright &copy; 2024 XU Exponential University of Applied Science
# nav:
# - Home: index.md
# - Setup: setup.md
# - Website:
#    - User Page: userpage.md
#    - Admin Page: adminpage.md
# - API: api.md
# - Our Build: build.md
# - Projects: pro.md
# - Research: re.md
# - Guide:
#    - Getting Started: getting-started.md
#    - Advanced Topics: advanced-topics.md

nav:
  - Home: index.md
  - Getting Started:
      - Prerequisites: getting-started/prerequisites.md
      - Installation: getting-started/installation.md
      - Running the App: getting-started/running-the-app.md
  - Architecture:
      - Overview: architecture/overview.md
      - Sequence Diagrams: architecture/sequence-diagrams.md
      - Database: architecture/database.md
  - Features:
      - User Pages: features/user-pages.md
      - Admin Pages: features/admin-pages.md
      - User Interface: features/ui.md
      - Map and Search: features/map-and-search.md
  - Components:
      - Frontend: components/frontend.md
      - Backend: components/backend.md
      - Building Blocks: components/building-blocks.md
  - Deployment:
      - Docker Setup: deployment/docker-setup.md
  - Development:
      - Git Workflow: development/git-workflow.md
      - Coding Standards: development/coding-standards.md
      - Testing: development/testing.md
  - Advanced Topics:
      - Kafka: advanced-topics/kafka.md
      - API Reference: advanced-topics/api-reference.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Glossary: glossary.md




markdown_extensions:
 - pymdownx.arithmatex:
    generic: true
 - pymdownx.tabbed:
    alternate_style: true
 - pymdownx.superfences:
    custom_fences:
     - name: mermaid
       class: mermaid
       format: !!python/name:pymdownx.superfences.fence_code_format
 - pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
 - pymdownx.inlinehilite
 - pymdownx.snippets
 - pymdownx.superfences
 - pymdownx.details
 - pymdownx.critic
 - pymdownx.caret
 - pymdownx.keys
 - pymdownx.mark
 - pymdownx.tilde
 - admonition
 - attr_list
 - md_in_html
 - tables
 - pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js



repo_url: https://github.com/MarieBelle88/GaiasCycle